### ISSUE TITLE
Release Steps

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/stlcsb#13]
Functions and unit testing:
- [x] Fix `csb_missingXY` so that it no longer relies on `options(scipen)`
- [x] Move `magritter` dependency to `dplyr` - update all `@importFrom` statements accordingly
- [x] Add code to ensure each function returns a tibble to all functions that could be used post data download
- [x] Remove `csb_intersection()` 
- [x] Update error messages to make them more informative for all functions 
- [x] Update unit testing to reflect new error messages, tibble return
- [x] Make sure all unit tests use `january_2018`
- [x] Make sure unit tests are explicitly checking quoting and un-quoting
- [x] Convert `january_2018` to the "tidy" formatting returned by `csb_get_data()`, update unit tests and examples accordingly

Documentation:
- [x] Add `index.Rmd` for website landing page with less detail (no example - see `areal` for differences)
- [x] Add quick example to `README.Rmd`
- [x] Add hex to package
- [x] Clean-up vignette (ensure changes @chris-prener has made are reflected)
- [x] Add new functions (`csb_load_variables()` and `csb_last_update()`) to vignette
- [x] Spell check all documentation files - `devtools::spell_check()`

Release steps:
- [x] Run package through `devtools::release_checks()`
- [x] Run package through Winbuilder
- [x] Update `NEWS.md`
- [x] Release what we've got as v0.1.0

Final steps:
- [x] Create branch for CRAN release
- [x] Create can comments document
- [x] Update version number in `DESCRIPTION`
- [x] Update install sections on `README.Rmd`, `index.Rmd`, and `vignettes/stlcsb.Rmd`
- [x] Rebuild documentation and site
- [x] Final R CMD check
- [x] submit to CRAN!

**Comment by bransonf** [comment]
I've gotten as far as I can comfortably, we'll discuss the very final steps next time we meet. In the meantime, the edits branch has what I think are the solutions to some of these points.

**Comment by chris-prener** [comment]
this is great @bransonf - why don't you go ahead an open up a PR and we'll talk over next / final steps tomorrow!

**Comment by chris-prener** [comment]
submitted!
