### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by walker** [slu-openGIS/stlcsb#8]
https://github.com/slu-openGIS/stlcsb/blob/6d9eed184d19b759f6d4cd2688f3a805eb346922/R/csb_categorize.R#L55

We're going to remove this category from the export in the near future. They're not technically CSB tickets. Facilities Maintenance issues made it into the auto-update by mistake.

**Comment by bransonf** [comment]
Thank you as always @walker for supporting the development of the package. I'll leave this issue open until I see a change in the data. Additionally, I'll implement the corrections in the documentation when I have a chance, and the package is on track to be finished and submitted to CRAN by the end of December.

**Comment by walker** [comment]
@bransof i’ll have to check in a couple hours, but I think you should already have seen the facilities maintenance tickets all drop off

**Comment by chris-prener** [comment]
thanks @walker - since it was used historically I want to leave it in - we can note in the documentation that this is no longer an active category

**Comment by bransonf** [comment]
Hey @walker, send me an email `branson.fox@slu.edu` with a description of the changes. Your definition of maintenance may be different than my implementation. If so, I would like to change our categorization to match this.

Thank you in advance.
